Resources:
  CacheTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${param:UUID}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      KeySchema:
        - AttributeName: id
          KeyType: HASH
